apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: name-virtual-host-ingress
spec:
  rules:
  - host: www.saidevsecops.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: my-services
            port:
              number: 80
  - host: gamut.saidevsecops.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: gamut-services
            port:
              number: 80
